apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopus-k8s-target
  annotations:
    codefresh.io/product: octo-agent
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/octopusdeploy
    chart: kubernetes-agent
    targetRevision: "2.*.*"
    helm:
      releaseName: octotargetcf
      parameters:
        - name: agent.acceptEula
          value: "Y"
        - name: agent.space
          value: "Default"
        - name: agent.serverUrl
          value: "https://johny.octopus.app/"
        - name: agent.serverCommsAddresses[0]
          value: "https://polling.johny.octopus.app/"
        - name: agent.bearerToken
          value: "eyJhbGciOiJQUzI1NiIsImtpZCI6IjRmOGY0MWZiN2M5MTQ4YjliMjk1MGYyMGMwYWNlMTU4IiwidHlwIjoiSldUIn0.eyJhdWQiOiJodHRwczovL2pvaG55Lm9jdG9wdXMuYXBwIiwiaXNzIjoiaHR0cHM6Ly9qb2hueS5vY3RvcHVzLmFwcCIsImV4cCI6MTc0NTM5NjYzOCwiaWF0IjoxNzQ1MzkzMDM4LCJuYmYiOjE3NDUzOTMwMzgsImp0aSI6IjA4NGNlNjUyYzE2OTQ2M2U5MGFhYjE0YmIwOTkzNWQ4Iiwic3ViIjoiN2RkNjAxZTItYWM5Yi00N2VjLTg5MDQtYjcyZjM3NzIyYTdhIn0.UMZ0gbsHjjNU0DknL9gaZ4fTcVkoAXJIOoW2W4g31SQ34VQjOLae2zDmLvbl5Q8gZZB3S31_hkUzQKX16CLepLEHOaLXOiv3VQyc1QnMMDblfyDcUgcHvendWjZzyE2QwMT8AkLNmlR9IQ70ud_-wLnxCWQCjJpuDTj0Aqg-Jgk8vEFoLvy4OASE5Q1Q6_D7fU9hliA6b009t4SQd44Sjx4bVD5gtUOppIj6_AkMnAwAiq7c_b5EQNq3_o6M1BVfFXIaJUI9LY-1cYCdUwnRczLYkTHM1gUG2hxmythrVrupYv0E05JOtiGTIFC52lCHYaM52yat9ZIwfGJCTi9_JA"
        - name: agent.name
          value: "OctoTargetCF"
        - name: agent.deploymentTarget.enabled
          value: "true"
        - name: agent.deploymentTarget.initial.environments
          value: "{development,test,staging,production}"
        - name: agent.deploymentTarget.initial.tags
          value: "{k8s-cf}"
        - name: kubernetesMonitor.enabled
          value: "true"
        - name: kubernetesMonitor.registration.serverApiUrl
          value: "https://johny.octopus.app/"
        - name: kubernetesMonitor.monitor.serverGrpcUrl
          value: "grpc://johny.octopus.app:8443"
        - name: kubernetesMonitor.registration.serverAccessToken
          value: "eyJhbGciOiJQUzI1NiIsImtpZCI6IjRmOGY0MWZiN2M5MTQ4YjliMjk1MGYyMGMwYWNlMTU4IiwidHlwIjoiSldUIn0.eyJhdWQiOiJodHRwczovL2pvaG55Lm9jdG9wdXMuYXBwIiwiaXNzIjoiaHR0cHM6Ly9qb2hueS5vY3RvcHVzLmFwcCIsImV4cCI6MTc0NTM5NjYzOCwiaWF0IjoxNzQ1MzkzMDM4LCJuYmYiOjE3NDUzOTMwMzgsImp0aSI6IjA4NGNlNjUyYzE2OTQ2M2U5MGFhYjE0YmIwOTkzNWQ4Iiwic3ViIjoiN2RkNjAxZTItYWM5Yi00N2VjLTg5MDQtYjcyZjM3NzIyYTdhIn0.UMZ0gbsHjjNU0DknL9gaZ4fTcVkoAXJIOoW2W4g31SQ34VQjOLae2zDmLvbl5Q8gZZB3S31_hkUzQKX16CLepLEHOaLXOiv3VQyc1QnMMDblfyDcUgcHvendWjZzyE2QwMT8AkLNmlR9IQ70ud_-wLnxCWQCjJpuDTj0Aqg-Jgk8vEFoLvy4OASE5Q1Q6_D7fU9hliA6b009t4SQd44Sjx4bVD5gtUOppIj6_AkMnAwAiq7c_b5EQNq3_o6M1BVfFXIaJUI9LY-1cYCdUwnRczLYkTHM1gUG2hxmythrVrupYv0E05JOtiGTIFC52lCHYaM52yat9ZIwfGJCTi9_JA"
        - name: kubernetesMonitor.registration.spaceId
          value: "Spaces-1"
        - name: kubernetesMonitor.registration.machineName
          value: "OctoTargetCF"

  destination:
    name: in-cluster
    namespace: octopus-target
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
