apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopus-k8s-target
  annotations:
    codefresh.io/product: octo-agent
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/octopusdeploy
    chart: kubernetes-agent
    targetRevision: "2.*.*"
    helm:
      releaseName: octotargetcfk8s
      parameters:
        - name: agent.acceptEula
          value: "Y"
        - name: agent.space
          value: "JohnyDemo"
        - name: agent.serverUrl
          value: "https://demo.octopus.app/"
        - name: agent.serverCommsAddresses[0]
          value: "https://polling.demo.octopus.app/"
        - name: agent.bearerToken
          value: "eyJhbGciOiJQUzI1NiIsImtpZCI6ImY1NGZiYmE5ZGVjMzQ3MTVhYjMyZWY2YTQ2ZGZhZThjIiwidHlwIjoiSldUIn0.eyJhdWQiOiJodHRwczovL2RlbW8ub2N0b3B1cy5hcHAiLCJpc3MiOiJodHRwczovL2RlbW8ub2N0b3B1cy5hcHAiLCJleHAiOjE3NDU0OTczOTIsImlhdCI6MTc0NTQ5Mzc5MiwibmJmIjoxNzQ1NDkzNzkyLCJqdGkiOiIwMDA3NzkwZGE5ODE0MGVmYTc5MDk3MGJlZTUxMjExNiIsInN1YiI6ImYzOWZkMjUyLWI0ZGYtNGM1OS1hM2VhLWYxMDNkZThiMDYwZCJ9.szq6oumOVECnPRHSGBb3ZusZ8eN5Ko8-GfkyBf7SD5j3VPdLtMVmRJyWliEQKSL6WYLxuhL70uNJlCYDU1ufevL2zLLEpRJSo8558XtbeE6cYLGYajhk70YVV2Iq0Jmb_v8cxXHSoyqWHeRwdMpEtfKp5HkzhQgKlmkCFJ82SRq_oWcHVjtafMjcpERcP--5Huy3v4asotRvSDeZi0V2xloPlOuz-mzqhN5hPl0Rl84Fy-qowcvAh4yu6qUdX_bHWFSuy8njinu1HarVDLDYk-IDy6VMq_c05efyHnm4QN7E-nW9nRXd-8bMGTOKLeJ9j2JqBhLqztb2hXtYHMkxgg"
        - name: agent.name
          value: "OctoTargetCFK8S"
        - name: agent.deploymentTarget.enabled
          value: "true"
        - name: agent.deploymentTarget.initial.environments
          value: "{development,test,production,dr}"
        - name: agent.deploymentTarget.initial.tags
          value: "{k8s-cf}"
        - name: kubernetesMonitor.enabled
          value: "true"
        - name: kubernetesMonitor.registration.serverApiUrl
          value: "https://demo.octopus.app/"
        - name: kubernetesMonitor.monitor.serverGrpcUrl
          value: "grpc://demo.octopus.app:8443"
        - name: kubernetesMonitor.registration.serverAccessToken
          value: "eyJhbGciOiJQUzI1NiIsImtpZCI6ImY1NGZiYmE5ZGVjMzQ3MTVhYjMyZWY2YTQ2ZGZhZThjIiwidHlwIjoiSldUIn0.eyJhdWQiOiJodHRwczovL2RlbW8ub2N0b3B1cy5hcHAiLCJpc3MiOiJodHRwczovL2RlbW8ub2N0b3B1cy5hcHAiLCJleHAiOjE3NDU0OTczOTIsImlhdCI6MTc0NTQ5Mzc5MiwibmJmIjoxNzQ1NDkzNzkyLCJqdGkiOiIwMDA3NzkwZGE5ODE0MGVmYTc5MDk3MGJlZTUxMjExNiIsInN1YiI6ImYzOWZkMjUyLWI0ZGYtNGM1OS1hM2VhLWYxMDNkZThiMDYwZCJ9.szq6oumOVECnPRHSGBb3ZusZ8eN5Ko8-GfkyBf7SD5j3VPdLtMVmRJyWliEQKSL6WYLxuhL70uNJlCYDU1ufevL2zLLEpRJSo8558XtbeE6cYLGYajhk70YVV2Iq0Jmb_v8cxXHSoyqWHeRwdMpEtfKp5HkzhQgKlmkCFJ82SRq_oWcHVjtafMjcpERcP--5Huy3v4asotRvSDeZi0V2xloPlOuz-mzqhN5hPl0Rl84Fy-qowcvAh4yu6qUdX_bHWFSuy8njinu1HarVDLDYk-IDy6VMq_c05efyHnm4QN7E-nW9nRXd-8bMGTOKLeJ9j2JqBhLqztb2hXtYHMkxgg"
        - name: kubernetesMonitor.registration.spaceId
          value: "Spaces-3087"
        - name: kubernetesMonitor.registration.machineName
          value: "OctoTargetCFK8S"

  destination:
    name: in-cluster
    namespace: octopus-target
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
