apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopus-k8s-agent
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/octopusdeploy/kubernetes-agent
    chart: kubernetes-agent
    targetRevision: "2.*.*"
    helm:
      releaseName: octopus-k8s-agent
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: octopus-worker-test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
