agent:
  acceptEula: "Y"
  space: "Default"
  serverUrl: "https://johny.octopus.app/"
  serverCommsAddresses:
    - "https://polling.johny.octopus.app/"
  bearerToken: "eyJhbGciOiJQUzI1NiIsImtpZCI6IjRmOGY0MWZiN2M5MTQ4YjliMjk1MGYyMGMwYWNlMTU4IiwidHlwIjoiSldUIn0.eyJhdWQiOiJodHRwczovL2pvaG55Lm9jdG9wdXMuYXBwIiwiaXNzIjoiaHR0cHM6Ly9qb2hueS5vY3RvcHVzLmFwcCIsImV4cCI6MTc0NDgxMzAyMCwiaWF0IjoxNzQ0ODA5NDIwLCJuYmYiOjE3NDQ4MDk0MjAsImp0aSI6IjMyZjZhZjY2M2E0YTQzOWM5ZmIzYWYxMGQ2N2UyZTg1Iiwic3ViIjoiN2RkNjAxZTItYWM5Yi00N2VjLTg5MDQtYjcyZjM3NzIyYTdhIn0.Q_81yQ_WjvkgQT5t-NowW4u5AAptS6n6xJ2FUVWY08G99LW197O05D2kwK58IZRD3TLrFnDb9WYxT-ZSK_H9EEFJHqrdU-kGl8X34E_09hItPY735Md3f7em8v4mphyI6jMxMWlIxzLmfA6OKn6Ktxntlx7fyt8tVR-Wt5R2Q_7W2XaZvrabVB1zyCjF7EXfLj44xxf0BO1cOLhWn2JewiC648DJjwu09D-VZn_IUfy5m-4uZkqfnQfV0BU42RCbapA7LXWwxB5NV1yd1KUmHJEDXfT_NVC55INUFsfg-MS_tWnaUYcY8-KKxKFbHC-xuj1jZttjxm6jaAw_6vd3Ig"
  name: "OctoAgentCF"
  worker:
    enabled: true
    initial:
      workerPools:
        - test
